/*import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/login');
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('ivandro@gmail.com');
  await page.getByRole('textbox', { name: 'Senha' }).click();
  await page.getByRole('textbox', { name: 'Senha' }).fill('iv1234');
  await page.getByRole('textbox', { name: 'Senha' }).press('Enter');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('link', { name: 'Health Clinic Orientador' }).click();
  await page.getByRole('button', { name: 'Aprovar' }).click();
  await page.locator('#pr_id_2').getByRole('button').click();
  await page.getByLabel('Sair').click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('souto@g');
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('souto@gmail.com');
  await page.getByRole('textbox', { name: 'Senha' }).click();
  await page.getByRole('textbox', { name: 'Senha' }).fill('ir1234');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('combobox').selectOption('23');
  await page.getByRole('link', { name: 'Health Clinic Orientador' }).click();
  await page.getByRole('button', { name: 'Aprovar' }).click();
  await page.locator('#pr_id_2').getByRole('button').click();
  await page.getByLabel('Sair').click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('sebastiao@ucan.edu');
  await page.getByRole('textbox', { name: 'Senha' }).click();
  await page.getByRole('textbox', { name: 'Senha' }).fill('se1234');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('sebastiao@ucan.edu');
  await page.getByRole('textbox', { name: 'Senha' }).click();
  await page.getByRole('textbox', { name: 'Senha' }).fill('Se1234');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('#pr_id_2').getByRole('button').click();
  await page.getByLabel('Sair').click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('goncalves@gmail.com');
  await page.getByRole('textbox', { name: 'Senha' }).click();
  await page.getByRole('textbox', { name: 'Senha' }).fill('ma1234');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('link', { name: 'Health Clinic Orientador' }).click();
  await page.getByRole('button', { name: 'Aprovar' }).click();
  await page.locator('#pr_id_2').getByRole('button').click();
  await page.getByLabel('Sair').click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('iv');
  await page.getByRole('textbox', { name: 'Email' }).dblclick();
  await page.getByRole('textbox', { name: 'Email' }).fill('alex@gmail.com');
  await page.getByRole('textbox', { name: 'Senha' }).click();
  await page.getByRole('textbox', { name: 'Senha' }).fill('al1234');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('link', { name: 'Health clinic Orientador:' }).click();
  await page.getByRole('button', { name: 'Actualizar Relatório Final' }).click();
  await page.locator('span').filter({ hasText: 'Fazer o upload do relatório' }).first().click();
  await page.locator('span').filter({ hasText: 'Fazer o upload do relatório' }).first().setInputFiles('8_relatorio_final_1735280357154_FR-Impressão-FRM 5CL2024_2.pdf');
  await page.getByText('Fazer o upload do código/').click();
  await page.locator('span').filter({ hasText: 'Fazer o upload do código/' }).first().setInputFiles('config.zip');
  await page.getByRole('button', { name: 'Salvar Alterações' }).click();
  await page.getByRole('tab', { name: 'Tarefas e Avaliações' }).click();
  await page.getByRole('row', { name: 'undefined 23 Implementar os' }).getByLabel('Completar').click();
  await page.getByRole('dialog', { name: 'Completar Tarefa' }).getByRole('button').click();
  await page.getByRole('link', { name: ' Início' }).click();
  await page.getByRole('link', { name: 'Health clinic Orientador:' }).click();
  await page.getByRole('tab', { name: 'Tarefas e Avaliações' }).click();
  await page.getByRole('row', { name: 'undefined 23 Implementar os' }).getByLabel('Completar').click();
  await page.getByText('Seleccionar Ficheiro (s)').click();
  await page.locator('span').filter({ hasText: 'Seleccionar Ficheiro (s)' }).first().setInputFiles('Captura de ecrã de 2025-04-30 00-46-36.png');
  await page.getByText('Seleccionar Ficheiro (s)').click();
  await page.locator('span').filter({ hasText: 'Seleccionar Ficheiro (s)' }).first().setInputFiles('Captura de ecrã de 2025-04-29 12-41-55.png');
  await page.getByLabel('Enviar').click();
  await page.locator('#pr_id_2').getByRole('button').click();
  await page.getByLabel('Sair').click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('ivando@gmail.com');
  await page.getByRole('textbox', { name: 'Senha' }).click();
  await page.getByRole('textbox', { name: 'Senha' }).fill('iv1234');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('ivandro@gmail.com');
  await page.getByRole('textbox', { name: 'Senha' }).click();
  await page.getByRole('textbox', { name: 'Senha' }).fill('iv1234');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('.col-12 > .py-3').click();
  await page.getByRole('tab', { name: 'Tarefas e Avaliações' }).click();
  await page.getByRole('button', { name: 'Avaliar' }).click();
  await page.getByRole('textbox', { name: 'Escreva seus comentários aqui' }).click();
  await page.getByRole('textbox', { name: 'Escreva seus comentários aqui' }).fill('teste');
  await page.getByRole('spinbutton', { name: 'Atribua uma nota (0 a 100)' }).click();
  await page.getByRole('button', { name: 'Enviar Avaliação' }).click();
  await page.goto('http://localhost:3000/projecto-visualizar/24');
  await page.getByRole('button', { name: 'Atribuir Tarefas' }).click();
  await page.locator('span').filter({ hasText: 'Selecione uma opção' }).click();
  await page.getByText('Selecionar Tarefa').click();
  await page.getByText('Selecione as tarefas').click();
  await page.getByText('Implementar os diagramas de').click();
  await page.locator('#pr_id_31_content').click();
  await page.getByRole('button', { name: 'Atribuir Tarefa', exact: true }).click();
});*/
